name: KiCad_hardware_docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'hardware/BikeUSBv2.kicad_sch'
      - 'hardware/BikeUSBv2.kicad_pcb'

jobs:

# TODO: iBOM generation

#  FabPCB:
#    name: PCB fabrication files
#    runs-on: ubuntu-latest
#    container: ghcr.io/inti-cmnb/kicad7_auto
#    needs: setupGHP # DRC
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Run PCB stuff
#      run: |
#        [ -f hardware/*.kicad_pcb ] && kiplot  -d Fabrication -s all print_front gerbers
#
#    - name: Retrieve results
#      uses: actions/upload-artifact@v4
#      with:
#        name: FabPCB
#        path: Fabrication


  DocSch:
    name: Schematic for documentation
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto
    steps:
      - uses: actions/checkout@v4

      - name: make output folder
        run: |
          mkdir schematic_svg

      - name: export schmatic SVG
        run: |
          kicad-cli sch export svg --output schematic_svg hardware/BikeUSBv2.kicad_sch

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: schematic_svg
          path: schematic_svg


  DocPCB:
    name: PCB renders for Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: render pcb image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: hardware/BikeUSBv2.kicad_pcb
          output_path: ${{ github.workspace }}/pcb_renders

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pcb_renders
          path: pcb_renders

  DocPCB_GIF:
    name: PCB GIF for Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: render pcb GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: hardware/BikeUSBv2.kicad_pcb
          output_path: ${{ github.workspace }}/pcb_gif
          animation: gif

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pcb_gif
          path: pcb_gif

  deploy-pages:
    name: Deploy everything to GitHub Pages
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [DocPCB, DocSch, DocPCB_GIF] # FabBOM FabPCB
      
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Download schematic SVG
        uses: actions/download-artifact@v4
        with:
          name: schematic_svg

      - name: Download PCB renders
        uses: actions/download-artifact@v4
        with:
          name: pcb_renders

      - name: Download PCB GIF
        uses: actions/download-artifact@v4
        with:
          name: pcb_gif

      - name: Upload GitHub Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
