name: KiCad_CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'hardware/BikeUSBv2.kicad_sch'
      - 'hardware/BikeUSBv2.kicad_pcb'
#  pull_request:
#    branches: [ main ]
#    paths:
#      - 'hardware/BikeUSBv2.kicad_sch'
#      - 'hardware/BikeUSBv2.kicad_pcb'

jobs:
  setupGHP:
    name: Set up GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3


#  ERC:
#    runs-on: ubuntu-latest
#    container: ghcr.io/inti-cmnb/kicad7_auto
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Run ERC
#      run: |
#        [ -f hardware/*.sch ] && kiplot  -d Fabrication -s update_xml,run_erc -i
#
#    - name: Retrieve results
#      uses: actions/upload-artifact@v4
#      with:
#        name: ERC
#        path: Fabrication


#  DRC:
#    runs-on: ubuntu-latest
#    container: ghcr.io/inti-cmnb/kicad7_auto
#    needs: ERC
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Run DRC
#      run: |
#        [ -f hardware/*.kicad_pcb ] && kiplot  -d Fabrication -s update_xml,run_drc -i
#
#    - name: Retrieve results
#      uses: actions/upload-artifact@v4
#      with:
#        name: DRC
#        path: Fabrication

# TODO: iBOM generation

#  FabPCB:
#    name: PCB fabrication files
#    runs-on: ubuntu-latest
#    container: ghcr.io/inti-cmnb/kicad7_auto
#    needs: setupGHP # DRC
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Run PCB stuff
#      run: |
#        [ -f hardware/*.kicad_pcb ] && kiplot  -d Fabrication -s all print_front gerbers
#
#    - name: Retrieve results
#      uses: actions/upload-artifact@v4
#      with:
#        name: FabPCB
#        path: Fabrication
#    - name: Upload Artifact
#      if: github.ref == 'refs/heads/main'
#      uses: actions/upload-pages-artifact@v1
#      with:
#        name: FabPCB
#        path: "Fabrication"


  DocSch:
    name: Schematic for documentation
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto
    needs: setupGHP #ERC

    steps:
      - uses: actions/checkout@v4

      - name: make output folder
        run: |
          mkdir schematic_svg

      - name: export schmatic SVG
        run: |
          kicad-cli sch export svg --output schematic_svg hardware/BikeUSBv2.kicad_sch

      - name: Upload regular artifact
        uses: actions/upload-artifact@v4
        with:
          name: DocSch
          path: schematic_svg
      - name: Upload GitHub Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: schematic_svg


  DocPCB:
    name: PCB renders for Documentation
    runs-on: ubuntu-latest
    needs: setupGHP
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: render pcb image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: hardware/BikeUSBv2.kicad_pcb
          output_path: ${{ github.workspace }}/pcb_renders

      - name: Upload regular artifact
        uses: actions/upload-artifact@v4
        with:
          name: DocPCB
          path: pcb_renders
      - name: Upload GitHub Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: pcb_renders


  deploy-pages:
    name: Deploy everything to GitHub Pages
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [setupGHP, DocPCB, DocSch] # FabPCB FabBOM
      
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
